version: '3.9'

x-default-logging: &default-logging
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"

services:
  redis-db:
    <<: *default-logging
    extends:
      file: ./services/redis.yml
      service: redis-db

  db-init:
    <<: *default-logging
    extends:
      file: ./services/db.yml
      service: db-init

  db:
    <<: *default-logging
    depends_on:
      db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/db.yml
      service: db

  backend:
    <<: *default-logging
    depends_on:
      - db
      - redis-db
    extends:
      file: ./services/backend.yml
      service: backend
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        RELEASE_VERSION: 8.1.1
    links:
      - db:database
    environment:
        ETHEREUM_JSONRPC_HTTP_URL: http://host.docker.internal:8545/
        ETHEREUM_JSONRPC_TRACE_URL: http://host.docker.internal:8545/
        ETHEREUM_JSONRPC_WS_URL: ws://host.docker.internal:8545/
        CHAIN_ID: '1337'

  nft_media_handler:
    <<: *default-logging
    depends_on:
      - backend
    extends:
      file: ./services/nft_media_handler.yml
      service: nft_media_handler
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        RELEASE_VERSION: 8.1.1

  visualizer:
    <<: *default-logging
    extends:
      file: ./services/visualizer.yml
      service: visualizer

  sig-provider:
    <<: *default-logging
    extends:
      file: ./services/sig-provider.yml
      service: sig-provider

  frontend:
    <<: *default-logging
    depends_on:
      - backend
    extends:
      file: ./services/frontend.yml
      service: frontend

  stats-db-init:
    <<: *default-logging
    extends:
      file: ./services/stats.yml
      service: stats-db-init

  stats-db:
    <<: *default-logging
    depends_on:
      stats-db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/stats.yml
      service: stats-db

  stats:
    <<: *default-logging
    depends_on:
      - stats-db
      - backend
    extends:
      file: ./services/stats.yml
      service: stats

  user-ops-indexer:
    <<: *default-logging
    depends_on:
      - db
      - backend
    extends:
      file: ./services/user-ops-indexer.yml
      service: user-ops-indexer

  proxy:
    <<: *default-logging
    depends_on:
      - backend
      - frontend
      - stats
    extends:
      file: ./services/nginx.yml
      service: proxy
